name: Build and Push to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: 'eu-west-1'
  ECR_REPOSITORY: 'lampstack'
  CONTAINER_NAME: 'lampstack_container'
  ECR_REGISTRY: '288761743924.dkr.ecr.eu-west-1.amazonaws.com'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::288761743924:role/github-actions-lambda-role
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: github-actions-ecr-push

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

    - name: Change Directory
      run: cd LAMP_STACK_PHP_CODE

    - name: Build Docker image
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }} .
        
    - name: Tag Docker image
      run: |
        docker tag ${{ env.ECR_REPOSITORY }}:latest \
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        docker tag ${{ env.ECR_REPOSITORY }}:latest \
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Push Docker images
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}